name: Check project

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: "Project check"
            run: |
              npm i
              npm run check

